---
# tasks file for egeneralov.k3s

- name: /etc/hosts
  lineinfile:
    path: /etc/hosts
    line: "{{ hostvars[item].ansible_default_ipv4.address }} {{ item }}"
  with_items: "{{ groups['k3s'] }}"

- name: Set hostname
  hostname:
    name: "{{ inventory_hostname }}"

- import_tasks: install.yml

- include_tasks: local-pv.yml
  when: inventory_hostname in groups['k3s-master'] and k3s_install_local_provisioner == true

- include_tasks: helm.yml
  when: inventory_hostname in groups['k3s-master'] and k3s_install_helm == true
